vagrant: false

# Change this file to add dependency artifacts, repos, & roles!
repo: [
  { repo: "https://github.com/Uni-Apps/Browser.git", name: "Browser"},
  { repo: "https://github.com/Source-Graph/VisualStudioCode.git", name: "VisualStudioCode"},
  ]

role: [
  { git: "Browser", name: "Browser", path: "src/ansible/roles/Browser"},
  { git: "VisualStudioCode", name: "Visual Studio Code", path: "src/ansible/roles/Visual Studio Code"},
  ]

library: [
  # { git: "getGPU", name: "get_gpu.py", path: "src/ansible/library"},
  ]

# set Inventory "{{static_inventory}}"
dynamic_inventory: hosts
test_inventory: true

# dependencies
git_fetch_update: true

# extra_files_touch: ["{{ playbook_dir }}/roles/get/vars/override.yml"]
